### ISSUE TITLE
Feature Request: Allow all subdomains of a given domain

### ISSUE THREAD

**Issue by aleskiontherun** [haproxytech/haproxy-lua-cors#10]
Sometimes it's not super convenient to maintain a large changing list of subdomains in CORS configuration, so it would be great to be able to specify just a base domain to allow requests from all its subdomains.

**Comment by NickMRamirez** [comment]
To keep the library simple, I prefer to not add extra functionality that is outside the scope of vanilla CORS. If others agree it is an important feature, we can reopen the discussion.
