### ISSUE TITLE
Remove original CORS-header if present

### ISSUE THREAD

**Issue by kev-ac** [haproxytech/haproxy-lua-cors#17]
We are in a situation where our backend service always returns a CORS header. This is something we can't change.

This results in two _Access-Control-Allow-Origin_ headers in the response. 

I think the original header should be replaced if present in HAproxy.

**Comment by NickMRamirez** [comment]
Fixed with commit https://github.com/haproxytech/haproxy-lua-cors/commit/b3ffb2ac3dea36ef8c921a2d64e57dba6c3a80d8
