### ISSUE TITLE
Failing to set up HAProxy with backend servers not configured with CORS

### ISSUE THREAD

**Issue by Avik32223** [haproxytech/haproxy-lua-cors#2]
Thank you for providing such an amazing tool. The Lua script works pretty well for us.

I have been trying to setup HAProxy as a reverse proxy with backends which are not in my control (CORS not enabled on these servers).

I have been facing issues while setting up HAProxy with such servers. 
Adding this script to HAProxy works for the most part and preflight OPTIONS requests returns a list of HTTP verbs which I have configured. But, the requests are also forwarded to the backend which returns 405 since it is not configured to handle CORS. This renders this script useless because the browser will reject the response due to status code 405.

I maybe wrong in my assumptions or understanding and would like to have some guidance regarding this if possible.

Things that I have tried:
1. Created a placeholder/dummy backend section which returns an `errorfile` with a 200 HTTP response which works but it feels wrong to do so.
2. Update the Lua script to set 200 response code, with proper 'Access-Control-Allow-Headers' for preflight requests which works but feels wrong as well.

My setup is running on 
`HA-Proxy version 1.8.8-1ubuntu0.6 2019/10/23 18.04.1 LTS (Bionic Beaver)"`

Also, I am sorry if this is not the right forum to raise the question

**Comment by NickMRamirez** [comment]
Thanks @Avik32223. I will need to research this because, as it works now, it does not stop the request from going through to the backend server for an OPTIONS request. There may be a way to return it to the client via Lua code, though.

**Comment by Avik32223** [comment]
Thanks a lot for looking into this @NickMRamirez. 
As of now, things are working with the hacks I mentioned above 
But If you find a better way to handle this, please do share it.

**Comment by bedis** [comment]
Something you can try is to use a Lua service.
Just set a variable in your lua script with a value which indicates you want HAProxy to generate the response for said request, then use an acl to use the service if said variable is set to some value.

    http-request lua.cors
    http-request use-service lua.mydummyresponder if { var(txn.shouldianswer) true }

**Comment by bedis** [comment]
Or just use regular ACLs like `if METH_OPTIONS` to match all OPTIONS requests

**Comment by bmarkovic** [comment]
@Avik32223 

I believe my config-only CORS shim for HAProxy would work perfectly in your scenario. I've published it in a gist so have a look, try it and see if it works for you:

https://gist.github.com/bmarkovic/14aad2f5a68aebc4593d6bb4fc31337c

**Comment by Avik32223** [comment]
@bmarkovic I use a similar setup as you have mentioned in your gist. Though this works and really easy to implement, it feels a little hackish and wanted to check if there is a better approach. 

I feel adding a separate lua module to process preflight request as @bedis suggested feels a bit cleaner. I will go ahead with writing a new Lua service.

@bedis @bmarkovic Thanks a lot for your guidance. This has been really helpful

**Comment by NickMRamirez** [comment]
There is not a way for HAProxy to return a response from a Lua action, I've learned. It sounds like there are several work-arounds, though.

**Comment by bedis** [comment]
This is the purpose of a service to terminate a session in HAProxy and to return a response, so I don't really understand your statement.

**Comment by NickMRamirez** [comment]
@bedis Yes, I should have said "action" instead of "service".

**Comment by bedis** [comment]
I think you can edit your comment so we can clean up ours :)

**Comment by Avik32223** [comment]
Thanks for all your help. I really appreciate it.
