### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by nightvisi0n** [haproxytech/haproxy-lua-cors#22]
It looks like the example is not setting any ~~CSP~~ CORS header if I didn't misunderstood what this library should do:  

```shell
❯ curl -D- -X PUT -d test=test -H "Host: foo.bar" -H "X-Custom-Header: test" http://localhost:8080/putdata
HTTP/1.1 204 No Content
x-powered-by: Express
etag: W/"a-bAsFyilMr4Ra1hIU5PyoyFRunpI"
date: Mon, 15 Feb 2021 12:16:48 GMT
keep-alive: timeout=5

❯ curl -D- -X PUT -d test=test -H "Host: localhost" -H "X-Custom-Header: test" http://localhost:8080/putdata
HTTP/1.1 204 No Content
x-powered-by: Express
etag: W/"a-bAsFyilMr4Ra1hIU5PyoyFRunpI"
date: Mon, 15 Feb 2021 12:19:25 GMT
keep-alive: timeout=5
```

Shouldn't there be a difference between these two requests?

**Comment by NickMRamirez** [comment]
Hello, yes you have simply misunderstood. The purpose of this library is to set CORS headers and not the CSP header. Here's a blog post I found that describes the difference. https://www.devonblog.com/security/difference-between-cors-and-csp-security-headers/

**Comment by nightvisi0n** [comment]
Hi, thanks for your fast response. :+1: 

> not setting any CSP header

Sorry, of course I meant CORS headers, not CSP. As you can see in my command line output above I'm setting different `Host` headers and I expect to see different responses from HAProxy, but it's the same in both cases. I'm still thinking that the example does not work how it should..

**Comment by NickMRamirez** [comment]
CORS does not base its responses on the Host header, but rather the Origin header.

**Comment by NickMRamirez** [comment]
If you have more questions, please re-open this issue. I will close it for now.
