### ISSUE TITLE
Lua function 'cors': runtime error: attempt to index a nil value

### ISSUE THREAD

**Issue by Linuxfabrik** [haproxytech/haproxy-lua-cors#23]
Seems to occur on simple GET requests.

Version 2.1

`Feb 27 09:52:58 localhost haproxy[37645]: Lua function 'cors': runtime error: /etc/haproxy/cors.lua:100: attempt to index a nil value (field 'origin') from /etc/haproxy/cors.lua:100 C function line 98.
Feb 27 09:52:58 localhost haproxy[37645]: Lua function 'cors': runtime error: /etc/haproxy/cors.lua:100: attempt to index a nil value (field 'origin') from /etc/haproxy/cors.lua:100 C function line 98.
Feb 27 09:52:58 localhost haproxy[37645]: Lua function 'cors': runtime error: /etc/haproxy/cors.lua:100: attempt to index a nil value (field 'origin') from /etc/haproxy/cors.lua:100 C function line 98.
Feb 27 09:52:58 localhost haproxy[37645]: Lua function 'cors': runtime error: /etc/haproxy/cors.lua:100: attempt to index a nil value (field 'origin') from /etc/haproxy/cors.lua:100 C function line 98.
Feb 27 09:52:58 localhost haproxy[37645]: Lua function 'cors': runtime error: /etc/haproxy/cors.lua:127: attempt to index a nil value (local 'transaction_data') from /etc/haproxy/cors.lua:127 C function line 125.
Feb 27 09:52:58 localhost haproxy[37645]: Lua function 'cors': runtime error: /etc/haproxy/cors.lua:127: attempt to index a nil value (local 'transaction_data') from /etc/haproxy/cors.lua:127 C function line 125.
Feb 27 09:52:58 localhost haproxy[37645]: Lua function 'cors': runtime error: /etc/haproxy/cors.lua:127: attempt to index a nil value (local 'transaction_data') from /etc/haproxy/cors.lua:127 C function line 125.
Feb 27 09:52:58 localhost haproxy[37645]: Lua function 'cors': runtime error: /etc/haproxy/cors.lua:127: attempt to index a nil value (local 'transaction_data') from /etc/haproxy/cors.lua:127 C function line 125.`

Version 2.0

`Feb 27 09:58:39 localhost haproxy[37670]: Lua function 'cors': runtime error: /etc/haproxy/cors.lua:95: attempt to index a nil value (field 'origin') from /etc/haproxy/cors.lua:95 C function line 93.
Feb 27 09:58:39 localhost haproxy[37670]: Lua function 'cors': runtime error: /etc/haproxy/cors.lua:95: attempt to index a nil value (field 'origin') from /etc/haproxy/cors.lua:95 C function line 93.
Feb 27 09:58:39 localhost haproxy[37670]: Lua function 'cors': runtime error: /etc/haproxy/cors.lua:121: attempt to index a nil value (local 'transaction_data') from /etc/haproxy/cors.lua:121 C function line 119.
Feb 27 09:58:39 localhost haproxy[37670]: Lua function 'cors': runtime error: /etc/haproxy/cors.lua:121: attempt to index a nil value (local 'transaction_data') from /etc/haproxy/cors.lua:121 C function line 119.
`

In v1.0 there are no such errors.

**Comment by NickMRamirez** [comment]
There are some changes not included in version 2.1. I need to create a new tag 2.2. Do you get the error with the latest version in the master branch?

**Comment by Linuxfabrik** [comment]
No, with that from master branch the lua script does not throw nil-errors anymore.

**Comment by NickMRamirez** [comment]
I pushed a new version, v2.2: https://github.com/haproxytech/haproxy-lua-cors/releases/tag/v2.2
