### ISSUE TITLE
Lua function 'cors': runtime error: /etc/haproxy/cors.lua:81: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by knnat** [haproxytech/haproxy-lua-cors#24]
Version 2.2
See this error on journalctl log:

Mar 04 22:54:12 sim haproxy[1194]: [ALERT] 062/225412 (1199) : Lua function 'cors': runtime error: /etc/haproxy/cors.lua:81: attempt to concatenate a nil value (local 'origin') from /etc/haproxy/cors.lua:81 global 'preflight_request_ver2', /etc/haproxy/cors.lua:123 C function line 102.

**Comment by NickMRamirez** [comment]
Thanks for reporting this. Can you give some more details?

* Which version of HAProxy
* Sample of HAProxy config
* Is the HTTP request constructed in any special way? (e.g. curl, if so, what's the command)

Possibly related to https://github.com/haproxytech/haproxy-lua-cors/issues/23 and https://github.com/haproxytech/haproxy-lua-cors/issues/18

**Comment by NickMRamirez** [comment]
I am not seeing this error when I test. If possible, please give more details about how you're getting the error.

**Comment by NickMRamirez** [comment]
I've reproduced it. If you send an OPTIONS request that is not a preflight request. I will fix it.
