### ISSUE TITLE
response header Access-Control-Allow-Origin not present

### ISSUE THREAD

**Issue by Garreat** [haproxytech/haproxy-lua-cors#26]
I have two comma-separated origins allowed in haproxy config:
```
frontend x
  http-request lua.cors  "*" "https://domain.com,https://domain.com:8084" "*"
  http-response lua.cors
```

When I visit my website, Access-Control-Allow-Origin header isn't there:
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: no-cache, no-store, must-revalidate
Content-Length: 2
Content-Type: application/json; charset=utf-8
Date: Tue, 26 Oct 2021 14:48:03 GMT
Expires: 0
Pragma: no-cache
Vary: Accept-Encoding
Strict-Transport-Security: max-age=63072000
X-Content-Type-Options: nosniff
Referrer-Policy: strict-origin-when-cross-origin
Origin: https://domain.com
```

Performing CORS test from different origin gives expected result (xhr failure), so the core functionality is there.
However, one would expect the Access-Control-Allow-Origin response header, as stated in README.md.

HA-Proxy version 1.8.8-1ubuntu0.11 2020/06/22
haproxy-lua-cors v2.2.1

**Comment by Garreat** [comment]
Digging deeper, I think it's desired behaviour. Depends if the browser sends the Origin header in the first place. Please correct me if I'm wrong and feel free to close this one. Thank you.

**Comment by Garreat** [comment]
Well I don't get it. Shouldn't this request fail? 
```
[user@localhost ~]$ curl -LI -H "Origin: https://domain123213.com" https://domain.com
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: no-cache
Content-Length: 2614
Content-Type: text/html; charset=utf-8
Date: Tue, 26 Oct 2021 16:49:26 GMT
Etag: "a7dac6f55423b8c9ec2dc6f0b32a2e566951551e"
Last-Modified: Tue, 26 Oct 2021 13:37:19 GMT
Vary: accept-encoding
Strict-Transport-Security: max-age=63072000
X-Content-Type-Options: nosniff
Referrer-Policy: strict-origin-when-cross-origin
Origin: https://domain.com
```
Same result on fresh HAproxy:
HAProxy version 2.4.7-1ppa1~bionic 2021/10/07 - https://haproxy.org/

**Comment by NickMRamirez** [comment]
Hi @Garreat You are correct, the code will simply bail if an Origin header is not given. All CORS requests should pass that, but sometimes during testing, people forget to add it themselves.

Curl may not fail the request. Failing a cross-origin HTTP request is implemented on the client-side by the browser. For example, HAProxy on the server side doesn't do any restricting and will send back the request just fine. It's up to the browser to then say, "Whoa. I just got a response back from the server, but by following the same-origin policy, I can not serve it to the user." So, really, the response goes all the way back to the client and is then stopped by the browser. Curl does not have the same protections.

However, that's not a big issue. The purpose of the same-origin policy is to protect a user from being tricked when they visit a malicious website. The malicious website would like to send an Ajax / Fetch request to the user's bank saying, "I'm the user, send money to my malicious account."  With curl, there's no unwitting user you're trying to fool. It's just you tricking yourself :-)

**Comment by Garreat** [comment]
Thank you @NickMRamirez , your reply helped me understand things.
In my case there also were backend services messing with response headers. I ended up conditionally clearing those with an acl to finally get desired results:
```
acl legal-response-allow-origin res.hdr(Access-Control-Allow-Origin) -m str ...
acl legal-response-allow-origin res.hdr(Access-Control-Allow-Origin) -m str ...
http-response del-header Access-Control-Allow-Origin if !legal-response-allow-origin
```

Now it's all good! Thank you again.
