### ISSUE TITLE
Response and Allow-Headers added

### ISSUE THREAD

**Issue by ValeryDubrava** [haproxytech/haproxy-lua-cors#3]
Browsers (chrome) respond with errors on CORS method without this line:
```
  txn.http:res_add_header("Access-Control-Allow-Headers", "Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With")
    txn.http:res_set_status(200) 
```

**Comment by NickMRamirez** [comment]
@ValeryDubrava Can you give more details about how this issue? I am not able to reproduce it.

**Comment by NickMRamirez** [comment]
@ValeryDubrava Can you provide more details? I am not able to reproduce this issue.

**Comment by NickMRamirez** [comment]
Closing for now, but we can reopen if the problem persists.
