### ISSUE TITLE
Version in release page doesn't work with HAProxy 2.2.25-50b5f5d

### ISSUE THREAD

**Issue by titansmc** [haproxytech/haproxy-lua-cors#30]
I had to pull the latest version from main branch in order to get cors working, the one in Releases section doesn't work with HAProxy 2.2.25-50b5f5d, I guess you should release one that supports current versions or advise people to pull it from main branch.

**Comment by NickMRamirez** [comment]
Hi @titansmc. What specifically isn't working on your end?

I modified the `docker-compose.example.yml` file to use the image `aproxytech/haproxy-ubuntu:2.2`, then did:

```
docker-compose -f docker-compose.example.yml pull
docker-compose -f docker-compose.example.yml up
```

When I go to http://localhost/ the example page is working for me.

**Comment by NickMRamirez** [comment]
Thank you for reporting this @titansmc. I also verified that the code in the repo works with HAProxy 2.2, and then created a new release, [v2.3](https://github.com/haproxytech/haproxy-lua-cors/releases/tag/v2.3).

Thanks!

**Comment by revanfreeman** [comment]
Not work with haproxy 1.6 core.register_action take only 3 args and i suppose to have other bugs. Please can you add in readme compatible version ?

**Comment by NickMRamirez** [comment]
@revanfreeman Thank you for reporting this. I have verified that this library will work with HAProxy 1.8 and newer, but not older versions due to the error you reported. I will update the README to indicate this.
