### ISSUE TITLE
NOSRV when I enable CORS 

### ISSUE THREAD

**Issue by AnassDriate** [haproxytech/haproxy-lua-cors#32]
Hello,

I have health check in all my backends, check inter 2s fall 3 rise 10 , when i enable CORS, i start getting NOSRV in the logs,
but still everything works as expected, just the logs get more complicated.

Regards,

**Comment by NickMRamirez** [comment]
HI @AnassDriate You're seeing log entries like this, right?

```
<134>Mar 31 02:25:33 haproxy[8]: 172.19.0.1:34866 [31/Mar/2023:02:25:33.784] 
api api/<NOSRV> 0/-1/-1/-1/0 204 255 - - LR-- 2/1/0/0/0 0/0 {http://localhost} "OPTIONS /putdata HTTP/1.1"
```

If so, this is normal.

This is a [CORS preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request), and is always an OPTIONS request. In versions prior to 2.2, this module had to allow the request to go all the way to the backend server, and then on its return trip to client, it would add the preflight response headers, such as `Access-Control-Allow-Methods`. In 2.2 and newer versions, this module can intercept a preflight request and respond directly to the client without relaying the request to the backend server. 

Although the new way is more efficient, it does show up in the logs as having not contacted a server (NOSRV). You can also see that the request was given the [session termination code](http://docs.haproxy.org/2.2/configuration.html#8.5) of "LR", which, from the documentation, means:

* L = the session was locally processed by haproxy and was not passed to a server.
* R = the proxy was waiting for a complete, valid REQUEST from the client (HTTP mode only). Nothing was sent to any server.

If you don't care to see OPTIONS requests in the log, you can add this line:

```
http-request set-log-level silent if { method OPTIONS }
```

**Comment by AnassDriate** [comment]
@NickMRamirez 

Thank you for your time and your feedback.

I see exactly what you described. and the NOSRV makes it hard to debug other issues ...

Unfortunately, your proposed solution does not work

**Comment by NickMRamirez** [comment]
Hi @AnassDriate 

Setting `http-request set-log-level silent` does not work? Can you say what the issue is that makes it not work?

**Comment by AnassDriate** [comment]
Hello @NickMRamirez 

I applied to the config you mentioned :  http-request set-log-level silent if { method OPTIONS } 

But i am still seeing NOSRV. I want to have clean logs in case of debug.

Thank you for your feedback

**Comment by NickMRamirez** [comment]
I need more information. Can you share your HAProxy configuration and log? Also the version of HAProxy you are using.

**Comment by NickMRamirez** [comment]
@AnassDriate Any update on this? Can you share the requested information?

**Comment by AnassDriate** [comment]
Hello @NickMRamirez 
Thank you for your feedback and sorry for my late reply, i took the time to test second time your proposition to be sure.
I added the config to the front-end of my haproxy : 
http-request set-log-level silent if { method OPTIONS }
But I see always NOSRV : 
```
Apr 13 16:00:25 XXX haproxy[790172]: xx:xxx:xxx:xxx:xx [13/Apr/2023:16:00:25.576] https-in~ matrix-well-known-client/<NOSRV>  0/-1/-1/-1/0 200 479 - - LR-- 6/5/0/0/3 0/0 "GET /.well-known/matrix/server HTTP/1.1"
Apr 13 16:00:26 XXX haproxy[790172]: xx:xxx:xxx:xxx:xx [13/Apr/2023:16:00:26.632] https-in~ matrix-well-known-client/<NOSRV>  0/-1/-1/-1/0 200 479 - - LR-- 8/6/0/0/3 0/0 "GET /.well-known/matrix/server HTTP/1.1"
```

**Comment by AnassDriate** [comment]
HA-Proxy version 2.2.9-2+deb11u4 2023/02/11 - https://haproxy.org/

**Comment by NickMRamirez** [comment]
I see from your log that this is not what I thought. These are GET requests, not OPTIONS requests. So, the line I gave you will not match these requests. On the surface, this looks unrelated to CORS. This CORS library should return immediately only for CORS preflight OPTIONS requests. It will  not do that for GET requests.

You say everything is working fine? I wonder if you have another component that is intercepting the request in HAProxy and returning it without contacting a backend server?  It seems related to Matrix. Is there a Matrix integration that is doing it? For example, do you have any `http-request return` lines in your configuration?

You can modify your config to ignore these types of requests with a directive like this:

```
http-request set-log-level silent if { path /.well-known/matrix/server }
```

**Comment by AnassDriate** [comment]
@NickMRamirez  Thank you for your feedback

Yes I confirm everything works fine. we do not have http-request return, we do not have something that return without checking the back, But what i noticed is because of `check inter 2s fall 3 rise 10` we have the check in all our backends. For curiousity i removed the checks to verify and it works correctly i did not see the NOSRV. 
This is what noticed it can be true it can be false. Do you think it can be related to the health checks ?

**Comment by NickMRamirez** [comment]
And your servers are passing their health checks? If all servers were down, that might cause it. Checking the [HAProxy Stats page](https://www.haproxy.com/blog/exploring-the-haproxy-stats-page/) could help.

**Comment by AnassDriate** [comment]
@NickMRamirez  thank you for your support 
I will check your suggestion
