### ISSUE TITLE
Setting Access-Control-Allow-Credentials on preflight requests

### ISSUE THREAD

**Issue by sripberger** [haproxytech/haproxy-lua-cors#5]
While configuring an API gateway for my company I've noticed something this library is doing that I find kind of strange.

It makes sense to set the `Access-Control-Allow-Methods` for preflight OPTIONS requests, since browsers only check this header for such requests.

https://github.com/haproxytech/haproxy-lua-cors/blob/443684f789ace9be2229a99f8c9d997885ec9bbb/lib/cors.lua#L39

I suppose it also makes sense to set `Access-Control-Max-Age` for similar reasons, since this is likewise only responsible for caching of preflight options requests, though it would be nice if this behavior were documented.

https://github.com/haproxytech/haproxy-lua-cors/blob/443684f789ace9be2229a99f8c9d997885ec9bbb/lib/cors.lua#L41

I'd not have noticed the Max-Age at all, though, if it wasn't for the problem I'm encountering because of this line:

https://github.com/haproxytech/haproxy-lua-cors/blob/443684f789ace9be2229a99f8c9d997885ec9bbb/lib/cors.lua#L40

What is the reasoning for setting this here? Obviously some people will not want to be accepting cookies with their API gateways, so in those cases this shouldn't be set at all. But even those cases that do want to accept credentials will need to *also* set this header on the actual responses, otherwise they get a situation where the full requests are actually being made, but the responses cannot be read.

If you make a cross-origin POST with credentials from Chrome using fetch, for example, you get this:

```
The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'.
```

Note this is happening with the actual request, not the preflight request. If you attempt to fix this by adding the following to your frontend config:

```
http-response add-header Access-Control-Allow-Credentials true
```

This ends up appending `, true` to the value of this header for the preflight, and you get this:

```
Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is 'true, true' which must be 'true' when the request's credentials mode is 'include'.
```

Of course, one can use `set-header` instead of `add-header` and just overwrite what is already there, and it will work fine:

```
http-response set-header Access-Control-Allow-Credentials true
```

It is, however, puzzling to me that this is happening at all. I can't imagine a situation where you would want it to add this header to preflight requests but not "real" requests, let alone having it be an undocumented behavior of this library.

**Comment by NickMRamirez** [comment]
I spent some time reading more about Access-Control-Allow-Credentials, and am I correct that it opts in for accepting cookies from client-side Ajax / Fetch calls? Which could open the door to CSRF?

What's your recommendation? That this library should default to _not_ setting this header at all? And leave it up to the user to add it to their HAProxy configuration?

**Comment by sripberger** [comment]
In this case I would say it's more a usability concern than a security concern. It is unlikely anybody will accidentally open themselves up to CSRF with this, because if they are using cookies they will have to be dealing with the Access-Control-Allow-Credentials header on their non-preflight responses anyway, as well as implementing CSRF-prevention techniques for non-Ajax requests (malicious links causing browser navigation for example). 

The Allow-Credentials header is interesting, though, because its presence affects browser behavior when it comes to other headers. If you set it to true, the browser will no longer accept "\*" for Allow-Origin or Allowed-Methods. This is sort of an attempt at idiot-proofing. Setting Allow-Credentials to true is telling the browser, "I'm aware of the CSRF risk, and I'm handling it." But using "*" for your Allow-Origin is clearly *not* handling it. So if browsers see this combination they will complain about it and block the request.

Setting this to true in all OPTIONS requests-- which is being done here-- will therefore cause problems for anybody using "*" to allow all origins. It won't interfere with simple requests, but it will block preflighted ones.

Meanwhile, if you actually do want this header to be set so that you can accept cookies from background requests, you need to set it on both the preflight request and the actual request. Otherwise, scripts running in the browser won't be allowed to read the results of the actual request.  The cors checks on the preflight response will pass, but the cors checks on the actual response will not.

To fix this problem you need to add an "http-response add-header" or "http-response set-header" line to your config anyway. As I showed, though, using `add-header` causes the config-provided value to collide with the one that is already present in preflight requests from the lua script.

So, yeah, my recommendation would be to just not set it at all by default. Since it's a super easy change, I'll have a PR up in a few moments. It will technically be a breaking change, though, so it's up to you what you'd like to do of course. :)
