### ISSUE TITLE
Cross-Origin Request Blocked:

### ISSUE THREAD

**Issue by rayj00** [haproxytech/haproxy-lua-cors#8]
So I using HAproxy to access LXD containers.  I installed the lua.cors directives into the haproxy.cfg but I am still getting the COR request blocked?  

**mydomain**.us is ficticious as I don't want traffic on my site right now.

website is an LXD container,  accessed with http or https://www.mydomain.us. The acl for website works fine with or without the cors.lua.  

broadcast is an LXD container running Ubuntu 18.04 and a nodejs app running on port 9001 and accessed with https://bcast.mydomain.us   I can get to the webpage, but it is producing the Cross-Origin Request Blocked and I cannot proceed from the page. Here is the error:

**Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost:9001/socket.io/?userid=1o1hbuzwazgacognu4f…imitPerUser=1&extra=%7B%7D&EIO=3&transport=polling&t=N8yWFI-. (Reason: CORS request did not succeed)**

I tried the "*" in the http-response but it did not help.

Here is my haproxy.cfg:

`global
    log 127.0.0.1 local0 notice info
    lua-load /etc/haproxy/cors.lua
    maxconn 2000
    tune.ssl.default-dh-param 2048
    user haproxy
    tune.maxrewrite     4096
    group haproxy

    ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
    ssl-default-bind-ciphers EECDH+AESGCM:EDH+AESGCM
    tune.ssl.default-dh-param 2048

defaults
    log global
    mode http
    option forwardfor
    option http-server-close
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  5000
    timeout server  5000
    timeout tunnel  2h  #this is for websocket connections, 2 hours inactivity timeout
    timeout client-fin 5000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_lb
  bind *:80
  http-request lua.cors
  http-response lua.cors "GET,PUT,POST" "bcast.mydomain.us"
  bind *:8888
# Test URI to see if its a letsencrypt request
    acl letsencrypt-acl path_beg /.well-known/acme-challenge/
    use_backend letsencrypt-backend if letsencrypt-acl

  bind *:443 ssl crt /etc/haproxy/certs

  acl website hdr(host) -i mydomain.us  www.mydomain.us
  acl broadcast hdr(host) -i bcast.mydomain.us
  use_backend mainweb if website
  use_backend bcast1 if broadcast

backend letsencrypt-backend
    server letsencrypt 127.0.0.1:8888

backend mainweb
  balance leastconn
  http-request set-header X-Client-IP %[src]
  redirect scheme https if ! { ssl_fc }
  server website website.lxd:80 check

backend bcast1
  balance leastconn
  http-request set-header X-Client-IP %[src]
  redirect scheme https if ! { ssl_fc }
  server broadcast1 broadcast.lxd:9001 check ssl verify none
`
I appreciate any comments or suggestions for fixing this.

Ray

**Comment by NickMRamirez** [comment]
Hi Ray. In the CORS error message, it says:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost:9001

Is your website making a request to *localhost:9001*? You do not have *localhost:9001* listed on the `http-response lua.cors` line. You have:

```
http-response lua.cors "GET,PUT,POST" "bcast.mydomain.us"
```

It should work with:

```
http-response lua.cors "GET,PUT,POST" "bcast.mydomain.us,localhost:9001"
```

**Comment by rayj00** [comment]
Hi Nick. Thanks for responding. I fixed the problem. I had an error in my client code.

 

Ray

**Comment by NickMRamirez** [comment]
Thanks Ray, I will close the issue in that case.
